# Generated by Django 5.2 on 2025-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
