# Generated by Django 5.2 on 2025-05-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0002_pup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pup',
            name='dob',
        ),
    ]
