# Generated by Django 5.2 on 2025-05-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0003_remove_pup_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePuppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='available_pups/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
