# Generated by Django 5.2 on 2025-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0004_availablepuppy'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablepuppy',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
