# Generated by Django 5.2 on 2025-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0005_availablepuppy_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
